Update build-calendar.yml

diff --git a/.github/workflows/build-calendar.yml b/.github/workflows/build-calendar.yml
--- a/.github/workflows/build-calendar.yml
+++ b/.github/workflows/build-calendar.yml
@@ -36,14 +36,14 @@ jobs:
         run: ls -R .
 
       - name: Commit updated ICS
-        run: |
-          if [ -f calendar/uci-2026.ics ]; then
-            git config user.name "GitHub Action"
-            git config user.email "actions@github.com"
-            git add calendar/uci-2026.ics
-            git commit -m "Update ICS" || echo "No changes"
-            git push
-          else
-            echo "ICS file missing — skipping commit"
-            exit 1
-          fi
+        shell: bash
+        run: if [ -f calendar/uci-2026.ics ]; then
+          git config user.name "GitHub Action";
+          git config user.email "actions@github.com";
+          git add calendar/uci-2026.ics;
+          git commit -m "Update ICS" || echo "No changes";
+          git push;
+        else
+          echo "ICS file missing — skipping commit";
+          exit 1;
+        fi
