Update build-calendar.yml

diff --git a/.github/workflows/build-calendar.yml b/.github/workflows/build-calendar.yml
--- a/.github/workflows/build-calendar.yml
+++ b/.github/workflows/build-calendar.yml
@@ -37,13 +37,4 @@ jobs:
 
       - name: Commit updated ICS
         shell: bash
-        run: if [ -f calendar/uci-2026.ics ]; then
-          git config user.name "GitHub Action";
-          git config user.email "actions@github.com";
-          git add calendar/uci-2026.ics;
-          git commit -m "Update ICS" || echo "No changes";
-          git push;
-        else
-          echo "ICS file missing — skipping commit";
-          exit 1;
-        fi
+        run: if [ -f calendar/uci-2026.ics ]; then git config user.name "GitHub Action"; git config user.email "actions@github.com"; git add calendar/uci-2026.ics; git commit -m "Update ICS" || echo "No changes"; git push; else echo "ICS file missing — skipping commit"; exit 1; fi
